import { useState } from 'react'
import { ArrowDownRight, ArrowRight, ArrowUpRight, Bell, Check, ChevronDown, CircleHelp, Clock3, Command, LayoutDashboard, LogOut, Menu, MoreHorizontal, Plus, Settings2, Target, TrendingUp, Users, X } from 'lucide-react'
import { Link, Navigate, useNavigate } from 'react-router-dom'
import Brand from '../components/Brand.jsx'
import { getSession, signOut } from '../auth/authService.js'

const activity = [
  { initials: 'JM', color: 'peach', name: 'Jordan Miles', action: 'completed', subject: 'Launch brief review', time: '12 min ago' },
  { initials: 'RK', color: 'mint', name: 'Riley Kim', action: 'shared an update on', subject: 'Q4 planning', time: '1 hour ago' },
  { initials: 'AL', color: 'lavender', name: 'Alex Lee', action: 'added a milestone to', subject: 'Customer research', time: 'Yesterday' },
]
const tasks = [{ title: 'Finalize launch priorities', team: 'Product launch', due: 'Today', done: false }, { title: 'Review customer insights', team: 'Research sprint', due: 'Tomorrow', done: false }, { title: 'Share weekly team update', team: 'Team operations', due: 'Oct 18', done: true }]

export default function Dashboard() {
  const session = getSession()
  const navigate = useNavigate()
  const [mobileNav, setMobileNav] = useState(false)
  const [showAll, setShowAll] = useState(false)
  const [priorities, setPriorities] = useState(tasks)
  const [priorityFormOpen, setPriorityFormOpen] = useState(false)
  const [newPriority, setNewPriority] = useState('')
  if (!session) return <Navigate to="/login" replace />
  function logout() { signOut(); navigate('/') }
  function addPriority(event) {
    event.preventDefault()
    const title = newPriority.trim()
    if (!title) return
    setPriorities([...priorities, { title, team: 'Your workspace', due: 'Today', done: false }])
    setNewPriority('')
    setPriorityFormOpen(false)
  }
  const firstName = session.name.split(' ')[0]
  const greeting = new Date().getHours() < 12 ? 'Good morning' : new Date().getHours() < 18 ? 'Good afternoon' : 'Good evening'
  const today = new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' }).toUpperCase()

  return (<div className="app-shell">
    <aside className={`app-sidebar${mobileNav ? ' sidebar-open' : ''}`}><div className="sidebar-brand-row"><Brand /><button className="icon-button sidebar-close" aria-label="Close sidebar" onClick={() => setMobileNav(false)}><X size={18} /></button></div><div className="workspace-switch"><span className="workspace-avatar">N</span><span><strong>Nexora Studio</strong><small>Free workspace</small></span><ChevronDown size={15} /></div><span className="sidebar-label">WORKSPACE</span><nav className="sidebar-nav" aria-label="Workspace navigation"><Link className="sidebar-link active" to="/dashboard"><LayoutDashboard size={17} /> Overview</Link><a className="sidebar-link" href="#projects"><Command size={17} /> Projects <span className="sidebar-count">4</span></a><a className="sidebar-link" href="#team"><Users size={17} /> Team</a><a className="sidebar-link" href="#notifications"><Bell size={17} /> Notifications <span className="notification-pip" /></a></nav><span className="sidebar-label sidebar-label-spaced">PERSONAL</span><nav className="sidebar-nav" aria-label="Personal navigation"><Link className="sidebar-link" to="/profile"><Settings2 size={17} /> Profile & settings</Link><a className="sidebar-link" href="mailto:hello@nexora.example"><CircleHelp size={17} /> Help & support</a></nav><div className="sidebar-bottom"><div className="sidebar-progress"><span>YOUR WEEK</span><strong>3 of 5 priorities</strong><div className="progress-track"><i style={{ width: '60%' }} /></div><small>A steady pace looks good.</small></div><button className="sidebar-user" onClick={() => navigate('/profile')}><span className="user-avatar">{session.name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase()}</span><span><strong>{session.name}</strong><small>{session.email}</small></span><MoreHorizontal size={18} /></button></div></aside>
    {mobileNav && <button className="sidebar-scrim" aria-label="Close navigation" onClick={() => setMobileNav(false)} />}
    <main className="dashboard-main"><header className="dashboard-topbar"><button className="icon-button dashboard-menu" aria-label="Open navigation" onClick={() => setMobileNav(true)}><Menu size={20} /></button><div className="breadcrumb"><span>Workspace</span><span>/</span><strong>Overview</strong></div><div className="topbar-actions"><span className="today-label"><span className="live-dot" /> All systems moving</span><button className="icon-button topbar-notification" aria-label="Notifications" onClick={() => document.getElementById('notifications')?.scrollIntoView({ behavior: 'smooth' })}><Bell size={18} /><i /></button><button className="topbar-profile" onClick={() => navigate('/profile')} aria-label="Open profile settings"><span className="user-avatar">{session.name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase()}</span><ChevronDown size={14} /></button></div></header>
      <div className="dashboard-content"><div className="dashboard-welcome"><div><span className="eyebrow">{today}</span><h1>{greeting}, {firstName}<span className="greeting-dot">.</span></h1><p>You’re making good progress. Here’s your week at a glance.</p></div><button className="button button-primary" onClick={() => { setPriorityFormOpen(true); document.getElementById('priorities')?.scrollIntoView({ behavior: 'smooth' }) }}><Plus size={16} /> Add a priority</button></div>
      <div className="demo-banner"><span className="demo-banner-icon"><ShieldCheckIcon /></span><p><strong>Demo workspace.</strong> This dashboard uses local browser data only. Connect a trusted authentication and data provider before using real accounts.</p><button onClick={logout} className="demo-logout"><LogOut size={15} /> Log out</button></div>
      <section className="stat-grid" aria-label="Workspace summary"><article className="stat-card"><div className="stat-card-top"><span>Active projects</span><span className="stat-icon stat-indigo"><Command size={17} /></span></div><strong>04</strong><div className="stat-foot"><span className="stat-trend"><TrendingUp size={14} /> 2 moving forward</span><span>vs last month</span></div></article><article className="stat-card"><div className="stat-card-top"><span>Team momentum</span><span className="stat-icon stat-green"><TrendingUp size={17} /></span></div><strong>82<span className="stat-unit">%</span></strong><div className="stat-foot"><span className="stat-trend"><TrendingUp size={14} /> 8% this month</span><span>looking good</span></div></article><article className="stat-card"><div className="stat-card-top"><span>Priorities done</span><span className="stat-icon stat-peach"><Target size={17} /></span></div><strong>12<span className="stat-suffix">/ 16</span></strong><div className="stat-foot"><span className="stat-trend">On a steady pace</span><span>this quarter</span></div></article></section>
      <div className="dashboard-columns"><section className="dashboard-panel priorities-panel" id="projects"><div className="panel-heading"><div><span className="eyebrow">KEEP THE FOCUS</span><h2>Your priorities</h2></div></div>{priorityFormOpen && <form className="priority-add-form" onSubmit={addPriority}><label className="field"><span className="visually-hidden">New priority</span><input autoFocus value={newPriority} onChange={event => setNewPriority(event.target.value)} placeholder="What needs your focus?" required /></label><button className="button button-primary button-small" type="submit">Add</button><button className="icon-button" type="button" aria-label="Cancel adding priority" onClick={() => setPriorityFormOpen(false)}><X size={16} /></button></form>}<div className="priority-list">{priorities.map((task, index) => <label className={`priority-item${task.done ? ' priority-complete' : ''}`} key={`${task.title}-${index}`}><input type="checkbox" checked={task.done} onChange={() => setPriorities(priorities.map((priority, taskIndex) => taskIndex === index ? { ...priority, done: !priority.done } : priority))} /><span className="priority-check"><Check size={13} /></span><span className="priority-copy"><strong>{task.title}</strong><small>{task.team}</small></span><span className={`priority-due${task.due === 'Today' ? ' due-today' : ''}`}><Clock3 size={13} />{task.due}</span></label>)}</div><button className="panel-link" onClick={() => setShowAll(!showAll)}>{showAll ? 'Showing all priorities' : 'View all priorities'} <ArrowRight size={15} /></button></section>
      <section className="dashboard-panel momentum-panel"><div className="panel-heading"><div><span className="eyebrow">A LOOK BACK</span><h2>Team momentum</h2></div><span className="select-period">Last 7 days</span></div><div className="momentum-score"><strong>82<span>%</span></strong><span className="momentum-change"><TrendingUp size={14} /> 8%</span><small>compared to last week</small></div><div className="chart-area" role="img" aria-label="Team momentum rose steadily across the week"><div className="chart-gridline line-1"><span>100</span></div><div className="chart-gridline line-2"><span>75</span></div><div className="chart-gridline line-3"><span>50</span></div><div className="chart-gridline line-4"><span>25</span></div><svg viewBox="0 0 470 145" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="var(--primary)" stopOpacity=".2" /><stop offset="100%" stopColor="var(--primary)" stopOpacity="0" /></linearGradient></defs><path d="M0 118 C35 110 39 75 78 86 S130 100 156 70 S207 75 235 58 S281 83 313 54 S370 62 391 34 S440 45 470 13 L470 145 L0 145Z" fill="url(#chartFill)" /><path d="M0 118 C35 110 39 75 78 86 S130 100 156 70 S207 75 235 58 S281 83 313 54 S370 62 391 34 S440 45 470 13" fill="none" stroke="var(--primary)" strokeWidth="2.5" vectorEffect="non-scaling-stroke" /><circle cx="470" cy="13" r="4" fill="var(--surface)" stroke="var(--primary)" strokeWidth="2" vectorEffect="non-scaling-stroke" /></svg></div><div className="chart-labels"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></section></div>
      <div className="dashboard-columns lower-columns"><section className="dashboard-panel activity-panel" id="notifications"><div className="panel-heading"><div><span className="eyebrow">GOOD THINGS ARE HAPPENING</span><h2>Team activity</h2></div><button className="panel-link panel-link-compact" onClick={() => setShowAll(!showAll)}>{showAll ? 'Less' : 'See all'} <ArrowRight size={14} /></button></div><div className="activity-list" id="team">{(showAll ? [...activity, ...activity.slice(0, 1)] : activity).map((item, index) => <article className="activity-item" key={`${item.subject}-${index}`}><span className={`activity-avatar avatar-${item.color}`}>{item.initials}</span><p><strong>{item.name}</strong> {item.action} <a href="#projects">{item.subject}</a></p><time>{item.time}</time></article>)}</div></section><section className="dashboard-panel insight-panel"><span className="insight-symbol"><ArrowUpRight size={18} /></span><span className="eyebrow">A THOUGHT FOR THE WEEK</span><h2>Small, clear steps add up to meaningful change.</h2><p>Make space to notice what’s already moving.</p><button onClick={() => navigate('/profile')}>Visit your settings <ArrowDownRight size={15} /></button></section></div>
      <footer className="dashboard-footer"><span>© {new Date().getFullYear()} Nexora</span><span>Your work, moving forward.</span><button onClick={logout}><LogOut size={14} /> Log out</button></footer></div></main></div>
  )
}

function ShieldCheckIcon() { return <Check size={17} /> }
